version: "3"
services:
  mongodb:
    image: mongo:4.1.1
    ports:
      - 27017:27017
    volumes:
      - ~/C:\data\db
  web:
    restart: always
    build: .
    env_file: .env
    ports:
      - "8080:3000"
    external_links:
      - mongo
    environment:
      NODE_ENV: development
    depends_on: 
      - mongo
    